### PR TITLE
Fix FindOdinData.cmake so it works

### PR DESCRIPTION
**Pull request by wnichols1**

### CODE REVIEW

**Comment by wnichols1** [comment]
I know there are three versions of odin-data floating around:
dls-controls
percival-detector
odin-detector

but I think they all use this new directory structure.

**Comment by ajgdls** [comment]
Does this change line up with the odin-data version present in the percival-detector collaboration?

That's the only fork that is important to this module.  The two additional versions are all forked from the same base and so simply represent different points in history.  dls-controls will generally be kept up to date during each shutdown at DLS.

We generally upgrade the percival-detector/odin-data fork to be aligned with the master only when there is enough of a change to make it worthwhile (perhaps once a year).  Also, we need to be able to get the software tested when we do this, so it relies on external testing (e.g. DESY).

Soon I believe Diamond will get access to a full set of hardware and at this point you could bring everything up to date.

**Comment by ajgdls** [comment]
Sorry I've just seen your last statement.  If that is true then this fix should be OK.  I'll check it out...

**Review by ajgdls — COMMENTED** [review]
Just to be clear. Are you sure ODINROOT shouldn't be pointing to the installed location and that the file structure in there is correct?

**Comment by wnichols1** [comment]
the directories are different in the install location - so you may be right. Where should I find it?

**Comment by ajgdls** [comment]
@wnichols1 has this been resolved yet?

**Comment by wnichols1** [comment]
yes, I think the dir structure in the install location IS different, and ODINROOT should point to the install location. So this fix is wrong. delete it.

**Pull request closed without merging**
